### ISSUE TITLE
Multiple submissions of the same page to different assignments breaks previous secret URLs

### ISSUE THREAD

**Issue by upats** [MaharaProject/moodle-assignsubmission_mahara#14]
I just noticed this--I am not sure if it's something that's existed the whole time or if it is just surfacing now.

When a student submits their mahara page to a moodle assignment, it generates the secret URL and everything is good.
If that student, in another course or the same course for a different assignment, submits the same page again, it breaks the secret URL that was previously generated.
It looks like in the DB, the mahara view_access table entry is being deleted but the Moodle database is still trying to use that old generated secret URL. This results in an "Access Denied" message when trying to view the less recently submitted page in Moodle.

The not-really-a-workaround workaround is to have the student resubmit their assignment that is giving the access denied message. This will refresh the stored secret URL and allow the teacher to view the page.

I can think of two potential solutions, though I'm sure there are more:

1. Keep re-using the same secretly-generated secret URL for a given Mahara page whenever that page is submitted to any assignment in Moodle. This would keep Secret URL sprawl from happening, since we would just re-use the same URL.

2. (probably the easier solution) Create a brand new secret URL for each Mahara page, every time it is submitted. This would obviously start filling up the view_access table in Mahara on big mahoodle sites, so it's probably not the ideal solution, unless there's some sort of expiration time.

This is using the newest v. of the plugins and on Moodle 2.8.7

**Comment by agwells** [comment]
Hi upats,

I think what you're describing is the same behavior I described in Issue 2: https://github.com/MaharaProject/moodle-assignsubmission_mahara/issues/2#issue-50483918

So, I'll mark this one as a duplicate.

Cheers,
Aaron

**Comment by upats** [comment]
Ahh! I completely forgot about that. But yeah, this seems to be another side effect of the locking issue. Dang...
