### ISSUE TITLE
Event handler doesn't unlock the assignment if it's graded 0

### ISSUE THREAD

**Issue by agwells** [MaharaProject/moodle-assignsubmission_mahara#17]
To replicate:

0. Create a Moodle assignment with the Mahara submission plugin, setting the locking settings to unlock after grading.
1. Student submits a Mahara page to Mahara assignment in Moodle
2. Teacher grades assignment with a "0"

Expected result: The Mahara page should unlock (because it is now graded)
Actual result: The Mahara page remains locked

This is caused because the unlocking code checks for empty($grade->grade) to see whether the teacher graded the assignment, or submitted it with no grade. The PHP "empty()" method returns true on null, empty string, undefined variable, OR the numeral "0".

**Comment by kabalin** [comment]
Cant check now, but might be intended behaviour. What if teacher
selected 'no grade' (just opened assignment and clicked submit without
changing anything)? Anyway, push the fix, I will check later if it works in
all cases.

**Comment by agwells** [comment]
If you're using a scale and you do "no grade", it gives $grade->grade == -1. If you're using numeric grading and you leave the grade field empty, it does $grade->grade == null.

I noticed this problem because my default test case is a jerky teacher who gives the student a 0 and writes mean feedback comments. ;)
