### ISSUE TITLE
Moodle 3.0 compatibility

### ISSUE THREAD

**Issue by agwells** [MaharaProject/moodle-assignsubmission_mahara#20]
Need to test the plugin against Moodle 3 and make any necessary upgrades.

**Comment by agwells** [comment]
No API changes seen in the Moodle 3.0 changelogs that seem like problems. And I've just now given the plugin (the version currently in the Moodle Plugin Database site) a run on Moodle 3.0 and found no problems.

So, I'll update the documentation and the database listing accordingly.

**Comment by agwells** [comment]
Done!

**Comment by kabalin** [comment]
Thanks Aaron!
