### ISSUE TITLE
Cannot revert to draft if no portfolio submission

### ISSUE THREAD

**Issue by roperto** [MaharaProject/moodle-assignsubmission_mahara#27]
Related to #25 

If the submission include files (or other types) but no portfolio, it cannot be reverted to draft.

Notice: Trying to get property of non-object in .../mod/assign/submission/mahara/locallib.php on line 748

**Comment by danmarsden** [comment]
@roperto does that patch fix this completely? - I presume so.... closing this off.

**Comment by roperto** [comment]
Hi @danmarsden 

This fixed the problem reverting draft, I didn't look much for similar issues in code (although in UI I couldn't find anything).
