### ISSUE TITLE
Add tag for version 1.3

### ISSUE THREAD

**Issue by porcospino** [MaharaProject/moodle-assignsubmission_mahara#29]
Hello

Please would you add a tag for release 1.3 (Build 2018053100)?

Many thanks,

Chris

**Comment by danmarsden** [comment]
we haven't generated tags in github for releases for quite a while, and we'd probably forget on future releases. is there a reason you don't want to track it against a branch name? - I'd be more inclined to generate branches than manage it using tags.

**Comment by porcospino** [comment]
I'm using `git subtree` to manage plug-ins, like this:

```
git remote add moodle-assignsubmission_mahara https://github.com/MaharaProject/moodle-assignsubmission_mahara
git subtree add --squash --prefix=mod/assign/submission/mahara moodle-assignsubmission_mahara release-1.3
```

Doing this means we can be absolutely sure which version we're using.  Referencing a branch isn't as exact.

**Comment by danmarsden** [comment]
we use subtrees here at catalyst too but use the branch name - I'm not clear on the advantages of using a tag like that - it means you are basically using a commit id (which you can do too). Most github repos with Moodle plugins that I've seen don't use tags and it's not something I'd be planning to add to the all the plugins I maintain. Happy for someone else with write access to the repo here to go and do it for the mahara plugin though. I'm just reluctant to do this because it's not something we are going to regularly maintain or remember to do in future.

**Comment by porcospino** [comment]
OK, no problem.  It's just that there are lots of tags already in this repo, and I thought it was just an oversight.  I'm happy to use the branch name.  Are you going to add a MOODLE_34_STABLE branch for version 1.3?

**Comment by danmarsden** [comment]
Usually I only generate a new branch off master when we need to deviate to support a different version - but I don't have any issues creating branches that are exactly the same as master if people really need them. - Would it make things easier for you if we had a MOODLE_34_STABLE branch here?

I've also attached a script that Matt Clarkson wrote that uses the moodle upgrade api to find updated plugins from the plugins db and list the subtree commands to update the plugin that you might find useful. It uses the branch name from the moodle.org plugins db for that release too - (as long as the dev remembers to add it) - we drop this into admin/cli and run on the command line.

**Comment by kabalin** [comment]
>  It's just that there are lots of tags already in this repo
Yep, we were adding them in the past.

IMO the repo looks a bit more organised with version tags in place, so I added missing tags for each version bump we had since 1.2.1. However, it is up to developer whether to tag commits, there are no rules.

**Comment by porcospino** [comment]
Many thanks @kabalin 

@danmarsden I can't see the script either.  I'd be very grateful if you could make this available as I'm updating our tree right now.

**Comment by danmarsden** [comment]
weird - not sure what github did to that... I've just dropped it here:
http://git.catalyst.net.nz/gw?p=moodle-r2.git;a=shortlog;h=refs/heads/mdl35-plugin-upgrade-script
under: admin/cli/upgrade-plugins.php

hope you find it useful!
