### ISSUE TITLE
When previewing assignment on Mahara from Moodle, occasionally times the session out instantly

### ISSUE THREAD

**Issue by Connor-Overt** [MaharaProject/moodle-assignsubmission_mahara#30]
An issue has revealed itself recently with the latest versions of this plugin on Moodle with the above symptoms. 

It seems to be very intermittent and usually happens when Mahara is open in another browser. 

Authentication to Mahara is done via Mahoodle Integration XMLRPC.

**Comment by HarryBleckert** [comment]
I obeserved the same problem.
Moodle 3.5 and Mahara 18.04.3

**Comment by Connor-Overt** [comment]
Just to confirm, 

Moodle version I am still experiencing on is 3.3.3

Mahara version is 17.04.4

**Comment by anitsirk** [comment]
Previewing doesn't work properly anymore (and hasn't for a long time as far as I know). Since we are phasing out this plugin and move to LTI, this issue won't be fixed.
