### ISSUE TITLE
Can't delete a mahara assignment if the Mahara site is down

### ISSUE THREAD

**Issue by agwells** [MaharaProject/moodle-assignsubmission_mahara#6]
I had this problem on a demo site. A Moodle & Mahara site were connected together via MNet. Some mahara assignments were set up on the Moodle site. Then the Mahara site had its database reset (on purpose), while the Moodle site was kept around because it had useful demo data in it.

The result was that the existing mahara assignments were broken, but they couldn't be deleted because attempts to delete do an mnet call which was throwing an exception.

To replicate:

1. Set up a Mahoodle instance, with the assignment submission plugin.
2. Create a Mahara assignment in the Moodle site
3. Submit a Mahara page to the assignment
4. Delete the Mahara site's database and reinstall
5. Attempt to delete the Mahara assignment in Moodle

Expected result: You should be able to delete the assignment (possibly with a warning message)
Actual result: You see an error message and the deletion fails.

**Comment by kabalin** [comment]
I think I saw something similar when submitted page (unlocked) was deleted in Mahara, then deteting corresponding assignment in Moodle was not possible. Thanks for fixing this!
